BEGIN;

CREATE CREATE TABLE IF NOT EXISTS "cinema"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"name" TEXT NOT NULL UNIQUE, 
"adress" TEXT NOT NULL,
"zip" TEXT NOT NULL,
"city" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "projection-room"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"room-name" TEXT NOT NULL,
"seat-quantity" INT NOT NULL,
"cinema_id" INT NOT NULL REFERENCES "cinema"("id")
);

CREATE TABLE IF NOT EXISTS "movie"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"title" TEXT NOT NULL UNIQUE,
"director" TEXT NOT NULL,
"year" INT NOT NULL,
"duration (mn)" INT NOT NULL 
);

CREATE TABLE IF NOT EXISTS "client"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"firstname" TEXT NOT NULL,
"lastname" TEXT NOT NULL,
"email" TEXT NOT NULL UNIQUE,
"password" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "price"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"category" TEXT NOT NULL UNIQUE,
"amount" FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS "payment"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"entitled" TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "session"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"movie_id" INT NOT NULL REFERENCES "movie"("id"),
"projection-room_id" INT NOT NULL REFERENCES "projection_room"("id"),
"date_time" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "booking"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"client_id" INT NOT NULL REFERENCES "client"("id"),
"session_id" INT NOT NULL REFERENCES "session"("id"),
"price_id" INT NOT NULL REFERENCES "price"("id"),
"nb_seat" INT NOT NULL
);
COMMIT;
