BEGIN;

-- Regex

DROP EXTENSION IF EXISTS unaccent;

CREATE EXTENSION unaccent;

CREATE DOMAIN TEXT_ONLY AS TEXT CHECK(unaccent(VALUE) ~ '^[A-Za-z \-]+$');
CREATE DOMAIN ALPHANUM AS TEXT CHECK(unaccent(VALUE) ~ '^[A-Za-z\ \-\#\d]+$');
CREATE DOMAIN TEXT_MAIL AS TEXT CHECK(VALUE ~ '(^[a-z\d\.\-\_]+)@{1}([a-z\d\.\-]{2,})[.]([a-z]{2,5})$');
CREATE DOMAIN POSTAL_REGEX AS TEXT CHECK (VALUE ~ '(?!^00)\d{5}$');
-- create domain text_pwd

-- Tables creation

CREATE TABLE IF NOT EXISTS "cinema"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"name" ALPHANUM NOT NULL UNIQUE, 
"adress" ALPHANUM NOT NULL,
"zip" TEXT NOT NULL,
"city" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "projection-room"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"room-name" TEXT NOT NULL,
"seat-quantity" INT NOT NULL,
"cinema_id" INT NOT NULL REFERENCES "cinema"("id")
);

CREATE TABLE IF NOT EXISTS "movie"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"title" TEXT NOT NULL UNIQUE,
"director" TEXT NOT NULL,
"year" INT NOT NULL,
"duration (mn)" INT NOT NULL 
);

CREATE TABLE IF NOT EXISTS "client"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"firstname" TEXT NOT NULL,
"lastname" TEXT NOT NULL,
"email" TEXT NOT NULL UNIQUE,
"password" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "price"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"category" TEXT NOT NULL UNIQUE,
"amount" FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS "payment"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"entitled" TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "session"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"movie_id" INT NOT NULL REFERENCES "movie"("id"),
"projection-room_id" INT NOT NULL REFERENCES "projection_room"("id"),
"date_time" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "booking"(
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"client_id" INT NOT NULL REFERENCES "client"("id"),
"session_id" INT NOT NULL REFERENCES "session"("id"),
"price_id" INT NOT NULL REFERENCES "price"("id"),
"nb_seat" INT NOT NULL
);
COMMIT;
